kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
  namespace: metrics
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: myapp
        scrape_interval: 10s
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: myapp
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod
