apiVersion: v1
kind: Service
metadata:
  name: autoscaling
spec:
  selector:
    app: autoscaling
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling
  template:
    metadata:
      labels:
        app: autoscaling
    spec:
      containers:
        - image: learnk8s/autoscaling:0-base
          name: autoscaling
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
