apiVersion: v1
kind: Service
metadata:
  name: autoscaling
spec:
  selector:
    app: autoscaling
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling
  template:
    metadata:
      labels:
        app: autoscaling
    spec:
      containers:
        - image: learnk8s/autoscaling:v1
          name: autoscaling
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          # This is necessary for autoscaling based on CPU utilisation
          resources:
            requests:
              cpu: 10m
